/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface AdminAuditEvents {
  action: string;
  actorId: number | null;
  createdAt: Generated<Timestamp>;
  details: Generated<Json>;
  entityId: string;
  id: Generated<Int8>;
}

export interface CatalogAudioFingerprints {
  sha256: string;
  trackId: string;
  updatedAt: Generated<Timestamp>;
}

export interface CatalogTelegramSources {
  audioSha256: string;
  channelId: string;
  importedAt: Generated<Timestamp>;
  importedBy: number;
  messageId: number;
  trackId: string;
}

export interface CatalogTracks {
  artist: string;
  artworkUrl: string | null;
  audioFilename: string | null;
  audioUrl: string | null;
  captions: Generated<Json>;
  captionsRevision: Generated<number>;
  coverFilename: string | null;
  createdAt: Generated<Timestamp>;
  createdBy: number | null;
  duration: Generated<number>;
  id: string;
  language: Generated<string>;
  revision: Generated<number>;
  sourceSubmissionId: string | null;
  status: Generated<string>;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface CatalogUploads {
  consumedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  expiresAt: Timestamp;
  files: Json;
  id: string;
  submissionId: string | null;
  trackId: string | null;
  userId: number;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean>;
}

export interface MuwaDiagnostics {
  area: string;
  build: string;
  errorCode: Generated<number>;
  errorType: string;
  id: string;
  occurredAt: Timestamp;
  platform: string;
  receivedAt: Generated<Timestamp>;
  userId: number;
  version: string;
}

export interface MuwaRequestLimits {
  attempts: number;
  bucket: string;
  updatedAt: Generated<Timestamp>;
  windowStart: Generated<Timestamp>;
}

export interface OwnerSetup {
  consumedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: Generated<boolean>;
  tokenHash: string;
}

export interface PremiumAccess {
  expiresAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface PremiumCodeAdmins {
  userId: number;
}

export interface PremiumCodeLimits {
  attempts: Generated<number>;
  userId: number;
  windowStart: Generated<Timestamp>;
}

export interface PremiumCodes {
  codeHash: string;
  createdAt: Generated<Timestamp>;
  createdBy: number;
  disabled: Generated<boolean>;
  durationDays: number;
  expiresAt: Timestamp;
  id: string;
  label: string;
  maxUses: number;
  uses: Generated<number>;
}

export interface PremiumRedemptions {
  codeId: string;
  redeemedAt: Generated<Timestamp>;
  userId: number;
}

export interface PublicationDrafts {
  artist: Generated<string>;
  audioKey: string | null;
  coverKey: string | null;
  createdAt: Generated<Timestamp>;
  id: string;
  language: Generated<string>;
  mediaSnapshot: Json | null;
  rejectionReason: string | null;
  revision: Generated<number>;
  status: Generated<string>;
  title: Generated<string>;
  trackId: string | null;
  updatedAt: Generated<Timestamp>;
  userId: number | null;
}

export interface PublicationUploads {
  contentType: string;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  draftId: string;
  expectedSha256: string | null;
  expiresAt: Timestamp;
  filename: string;
  id: string;
  part: string;
  sizeBytes: Int8;
  userId: number;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp>;
  userId: number;
}

export interface SubtitleVtwoCache {
  cacheKey: string;
  createdAt: Generated<Timestamp>;
  kind: string;
  leaseToken: string;
  leaseUntil: Timestamp;
  payload: Json | null;
}

export interface SubtitleVtwoLimits {
  calls: number;
  usageDay: Timestamp;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  adminAuditEvents: AdminAuditEvents;
  catalogAudioFingerprints: CatalogAudioFingerprints;
  catalogTelegramSources: CatalogTelegramSources;
  catalogTracks: CatalogTracks;
  catalogUploads: CatalogUploads;
  loginAttempts: LoginAttempts;
  muwaDiagnostics: MuwaDiagnostics;
  muwaRequestLimits: MuwaRequestLimits;
  ownerSetup: OwnerSetup;
  premiumAccess: PremiumAccess;
  premiumCodeAdmins: PremiumCodeAdmins;
  premiumCodeLimits: PremiumCodeLimits;
  premiumCodes: PremiumCodes;
  premiumRedemptions: PremiumRedemptions;
  publicationDrafts: PublicationDrafts;
  publicationUploads: PublicationUploads;
  sessions: Sessions;
  subtitleVtwoCache: SubtitleVtwoCache;
  subtitleVtwoLimits: SubtitleVtwoLimits;
  userPasswords: UserPasswords;
  users: Users;
}
